:sparkles: nested filters
tailflow/laravel-orion pull request #163
Opened 2022-07-11 12:32 UTC by GautierDele

Hello there,

We are having some trouble using orion because you basically can't handle priority on "or" and "and" on sql queries. This is problematic for us and we really need this to avoid custom routes on our project.

Here is my proposition for adding nested filters.

**What does it do ?**

This PR allows to add nested filters infinitely. Example of a search query:

```json
{
    "filters": [
        {"field": "is_for_all", "value": "true"},
        {
            "value": [
                {"field": "started_at", "operator": ">=", "value": "2022-05-23"},
                {"field": "ended_at", "operator": "<=", "value": "2022-06-23", "type": "or"}
            ],
            "type": "or"
        }
    ]
}
```

Your plugin is really well developed, it was really easy to implement.

**QUESTIONS:**

Do you have any idea how we could validate infinite arrays ? I basically removed requirement on filters and did not add nested validation.

There is a part in the app with "scopedFilters" and "filtersBuilder". It seems like replicating the Orion logic.Is it for open Api ? I did not took time to look at it and update it because i wanted your feedback on it.

Waiting for your feedback.

closes #126

2022-07-11 17:15 UTC, alexzarbn commented
Hi @GautierDele,

Thanks for the PR!

Answering your questions:
- I think in case of validating nested filters, it would require an additional (custom) rule that would traverse a given array of filters and apply validation rules dynamically, when it encounters another nested filter
- Yes, there are classes responsible for building OpenAPI specs, which would need to be updated too

To accept this PR, the following changes would be necessary:
1. Add an additional field `nested` instead of checking for the `value` property for two simple reasons: values can be arrays and not nested filters, having "something" reserved in the `value` field would affect existing apps logic
2. Implement proper `filters` array validation
3. Update OpenAPI specs generation to support nested filters
4. Integration tests for both model and relation resources to ensure it all works

2022-07-12 16:30 UTC, GautierDele commented
Hello @alexzarbn,

If you have any better idea than mine i'll take it for the nested validation.

I'll have a look at the open api specifications later since i never used it for now.

2022-07-13 07:37 UTC, GautierDele commented
Ok so basically i didn't quite like what i did because it wasn't explicit for user since it wasn't telling which field exactly was causing problem so now you are able to now exactly which field is wrong 
![image](https://user-images.githubusercontent.com/12382966/178677714-ff020c5b-07ae-4c63-8cc8-9fe0e46e5577.png)

2022-07-13 12:59 UTC, alexzarbn commented
@GautierDele 

Awesome, thank you! 

Aside from the requested changes, one question - what problems with nested queries do you refer to?
> I also added the ability to control the max depth to avoid problems in query (in config)

2022-07-13 14:53 UTC, GautierDele commented
@alexzarbn I refer mostly to a security / performance issue. Where the front could add a lot of nested filters and probably slow really much the application if he adds thousands of nested filters since the nested filters are theoretically infinite.

2022-07-13 17:13 UTC, GautierDele commented
On my side it's working fine but test arn't passing, is it normal ? I can see it's on other place of the app

2022-07-14 14:24 UTC, alexzarbn commented
@GautierDele 

It fails on my local setup too. There are two issues:

**The `config('orion.max_nested_depth')` usages in `ParamsValidator@validateFilters` are missing the default value.**

Can be fixed by including the following line of code in the `boot` method of `tests/Fixtures/Providers/OrionServiceProvider.php`:

```php
$this->mergeConfigFrom(__DIR__ . '/../../../../config/orion.php', 'orion');
```

**The `getting_a_list_of_resources_nested_filtered_by_not_whitelisted_field` test assertion is incorrect**

Can be fixed by changing assertion to:

```php
$response->assertJsonStructure(['message', 'errors' => ['filters.0.nested.0.field']]);
```

Also, please move the config key from `orion.max_nested_depth` to `orion.search.max_nested_depth` - there is already a group in the config for that. It currently has `case_sensitive` key only, but it would make sense to put that new key there too:

```php
'search' => [
   'case_sensitive' => true,
   'max_nested_depth' => 1,
],
```

2022-07-14 14:25 UTC, alexzarbn requested changes
@GautierDele 

It fails on my local setup too. There are two issues:

**The `config('orion.max_nested_depth')` usages in `ParamsValidator@validateFilters` are missing the default value.**

Can be fixed by including the following line of code in the `boot` method of `tests/Fixtures/Providers/OrionServiceProvider.php`:

```php
$this->mergeConfigFrom(__DIR__ . '/../../../../config/orion.php', 'orion');
```

**The `getting_a_list_of_resources_nested_filtered_by_not_whitelisted_field` test assertion is incorrect**

Can be fixed by changing assertion to:

```php
$response->assertJsonStructure(['message', 'errors' => ['filters.0.nested.0.field']]);
```

Also, please move the config key from `orion.max_nested_depth` to `orion.search.max_nested_depth` - there is already a group in the config for that. It currently has `case_sensitive` key only, but it would make sense to put that new key there too:

```php
'search' => [
   'case_sensitive' => true,
   'max_nested_depth' => 1,
],
```

2022-07-15 06:34 UTC, GautierDele commented
Moving "max_nested_depth" to the search is a breaking change because Laravel won't merge it in the service provider. Be sure to add it in the release process and increase middle version.

2022-07-15 06:38 UTC, GautierDele commented
In order to avoid this breaking change, i did set default value to 1.

2022-07-16 14:29 UTC, alexzarbn commented
@GautierDele,

Alright, thank you ~ I will merge the PR and resolve the remaining minor issues.

2022-07-16 14:29 UTC, merged

2022-07-16 14:44 UTC, GautierDele commented
Thanks !