[WIP] Rewrite resource spec generation to use Resource's properties
tailflow/laravel-orion pull request #172
Opened 2022-07-30 12:17 UTC by alkin

Current implementation generates the OpenApi Resource's specs basically as a copy of the model schema.

![image](https://user-images.githubusercontent.com/131324/181909017-fd5468a3-5361-408e-9890-c3f8165a1490.png)

Even though this is mostly correct, the resource may contain other properties that are not defined on the database, such as, loaded relations and computed properties. It may also contain less information than the schema, by making some of the properties hidden. Finally, the order in which the resource's properties are defined may differ from the database.

This PR rewrites the spec generation for the OpenApi Resource, based on the properties exposed by the resource itself. A basic type resolution for the additional properties is implemented. Better typing resolution may be implemented in the future.

**Work in Progress**
- [ ] Deal with conditional properties (merge and mergeWhen)
- [ ] Implement tests

2022-07-30 18:07 UTC, alkin commented
A final note on this: I am considering all properties from the resource, including the ones that would not be merged with mergeWhen. This behavior is closer to what is currently implemented. This can be configurable somehow in the future.

2022-08-03 14:36 UTC, alkin commented on src/ValueObjects/Specs/Schema/Properties/ObjectSchemaProperty.php
> +            'additionalProperties' => true,
See Free-form object in https://swagger.io/docs/specification/data-models/data-types/#object

2022-08-07 14:46 UTC, alexzarbn requested changes

2022-08-07 14:46 UTC, alexzarbn commented on src/Specs/Builders/Components/Model/ModelResourceComponentBuilder.php
> +        $component->title = class_basename($resourceResource);
It is missing the "Resource" suffix

2022-08-07 14:46 UTC, alexzarbn commented on tests/Unit/Specs/Builders/ComponentsBuilderTest.php
> +        $this->assertArrayHasKey('company', $resource);
What type the field would be in this case?

2022-08-08 16:28 UTC, alkin commented on src/Specs/Builders/Components/Model/ModelResourceComponentBuilder.php
> +        $component->title = class_basename($resourceResource);
Thank you for your review. Actually, this function receives two parameters now:

```php
public function build(Model $resourceModel, Resource $resourceResource): ModelResourceComponent
```

The variable `$resourceResource` is an instance of the Resource itself. Since i am getting the class name from the Resource (and not from the model, as before), the suffix is not needed.

2022-08-08 16:46 UTC, alkin commented on tests/Unit/Specs/Builders/ComponentsBuilderTest.php
> +        $this->assertArrayHasKey('company', $resource);
For the added properties, we generate a Resource using fake data and infer the types from this generated data. In this specific case we have:

```php
[
   'short_description' => substr($this->description, 90), // Will be inferred as "string"
   'company' => $this->whenLoaded('company', $this->company), // Willl be inferred as "object"
]
```

If the type can't be inferred (when the evaluated value is null for instance), the type is set to "any".

In the future, a better type resolution may be implemented. For instance, the `company` property could be typed as a `CompanyResource` and defined as `$ref: CompanyResource` in the specs.

2022-08-08 16:48 UTC, alkin commented on tests/Unit/Specs/Builders/ComponentsBuilderTest.php
> +        $this->assertArrayHasKey('company', $resource);
In a future PR, i will implement a better test for this, describing exactly the specs generated.

2022-08-15 14:00 UTC, alexzarbn commented
@alkin Please resolve conflicts and I will merge the PR

2022-08-15 14:10 UTC, alkin commented
@alexzarbn done :smiley:

2022-08-15 14:13 UTC, merged

2022-08-17 14:04 UTC, alexzarbn commented
@alkin I am afraid I have to revert this PR as it causes a lot of issues with specs generation in existing projects. Complex resource objects may contain additional method (calls) that rely on resource data, and if such resource data is invalid (e.g. `null`), it fails.
The only safe option for this would be to have an implementation that works with explicitly defined fields, rather than relying on `toArray()` and `optional()`.

2022-08-17 14:35 UTC, alkin commented
@alexzarbn It makes sense. Please consider if the following information helps in this case.

At the moment, I am creating the resource using an empty optional() object as base. All the calls executed inside the Resource are forwarded to this base object - which is usually a model - but in this case the empty optional object. The optional object accepts any method calls and return null, avoiding not implemented method exception. The same applies to attributes, returns null.

```php
[
  'id' => $this->id, // Returns null, the type will be inferred from the schema as int.
  'data' => $this->getData(), // This wont fail. The same as optional()->getData() which is null. Will be typed as any
  'other' => $this->otherInformation()->secondCall() // This will fail. But can be easily fixed by using the optional chain operator "?->" or the optional method
]
```

I could also try to fix the last case by implementing an "always optional" object, if you feel this is correct path.

I also agree with the explicitly defined fields and think its a great way to have finer control over the specs. I just think that this solution removes some benefits of the automatic specs generation. If we need to explicitly define all the resource properties we are not automating much.

Please let me know how you like to proceed.

2022-08-17 14:39 UTC, alkin commented
Another option to consider is to make this specs generation behaviour configurable in this version. The developer may choose if it wants the "simple" version, which results in the old specs, or the "improved" version, which gets the propertes from the resource. This approach could be useful to gather feedback and choose a single solution for the next major release.

2022-08-17 14:59 UTC, alkin commented
One other option that came to my mind would be to simply wrap the specs generation in a try catch block, ignoring null related exceptions. If there is any exception, the old default behavior would be used. This is not a perfect solution, but would enable us move forward with a better spec generation without worrying about exceptions.