:sparkles: aggregates support + filterable includes / aggregates
tailflow/laravel-orion pull request #184
Opened 2022-10-13 19:45 UTC by GautierDele

closes #127 

Hello,

Here you can find the PR to allow aggregates. This also includes filtering on aggregates / filters.

Two way of doing this:
Using query params (no filters):
```
localhost/api/users/search?include=posts&aggregateAvg=posts.id
```

Using post params (search):
```
{
    "aggregate": [
        {
            "relation": "posts",
            "type": "count",
            "filters": [
                {"field" : "created_at", "operator" : ">=", "value" : "2020-01-01"},
                {"nested": [
                    {"field": "id", "operator": ">", "value": 20},
                    {"field": "id", "operator": ">", "value": 21, "type": "or"}
                ]}
            ]
        },
        {
            "relation": "posts.id",
            "type": "avg",
            "filters": [
                {"field" : "created_at", "operator" : ">=", "value" : "2020-01-01"},
                {"nested": [
                    {"field": "id", "operator": ">", "value": 20},
                    {"field": "id", "operator": ">", "value": 21, "type": "or"}
                ]}
            ]
        },
        {
            "relation": "posts.id",
            "type": "sum"
        }
    ],
    "include": [
        {
            "relation": "posts",
            "filters": [
                {"field" : "created_at", "operator" : ">=", "value" : "2020-01-01"},
                {"nested": [
                    {"field": "id", "operator": ">", "value": 10},
                    {"field": "id", "operator": ">", "value": 11, "type": "or"}
                ]} 
            ]
        }
    ]
}
```

Nested filters are also possible on aggregates / includes.

A new param appear in the controller:
```php
    public function filterableBy(): array
    {
        return ['id', 'created_at'];
    }
```

Filters works natively with "filterableBy" present in controller.

I took time to refactor some of my previous code. I also rewrote the "include" part to make it compatible with post params and remove some duplicated code.

TODO IN PROGRESS:
- [ ] Documentation
- [ ] Testing

Please do not merge without these, i'm currently working on it

2022-10-13 21:48 UTC, GautierDele commented
@alexzarbn Do you have any idea why I have some checks (depending on PHP version and Laravel) that gives query params to 
```php
$request->post()
```
This was a requirement on my side to keep harmonisation, i'm quite confused this happens I didn't know about it

2022-10-15 21:34 UTC, GautierDele commented
@alexzarbn PR is almost ready i need to update tests for older versions, add documentation and change one bribe of logic in the app (see @TODO in code).
Could you make your code review while waiting since this feature is heavy ?

Thanks,
Gautier

2022-10-16 08:19 UTC, alexzarbn commented
Hi @GautierDele,

Thank you so much for the PR! The implementation looks great, let me review it in depth right now ~

2022-10-16 08:48 UTC, alexzarbn requested changes
Great and thorough implementation, amazing work, thank you! Mostly cosmetic changes would be required, but some (potentially minor) architectural issues are also present.

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/ParamsValidator.php
> +        $depth = $this->nestedFiltersDepth(RequestHelper::getPostRequestParam('aggregate', []), -1);
Let's keep it in plural form - `aggregates`, similar to other search parameters.

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/ParamsValidator.php
> +                    'aggregate.*.relation' => [
Perhaps we should stick with just `field` parameter here, because seeing something like `posts.id` inside `relation` field might be quite confusing. Do you think it is something achievable for this PR?

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/ParamsValidator.php
> +                'aggregateCount' => ['sometimes', 'string', 'not_regex:/\\./', new WhitelistedQueryFields($this->aggregatableBy)],
I would suggest to rename it to `with_count`, `with_min`, etc. to keep it consistent with other query parameters. What do you think?

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/ParamsValidator.php
> +    public function validateIncludes(Request $request): void
This is amazing 🔥 Now it would be possible to conditionally include relations, which is sooo good :)

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/QueryBuilder.php
> +    protected function usingTable($table, $callback) {
This seems like a bit of a hack to me. What is the reason for explicitly defining a table to use in query builder?

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/QueryBuilder.php
> +    public function getQualifiedFieldNameFromRelation(string $relation):string
This method returns table name of a relation, not a fully-qualified field. Either the naming is incorrect, or the implementation.

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/QueryBuilder.php
> +                "Aggregate queries are only supported with Laravel 8 and later"
I am pretty sure aggregates are supported with earlier versions too. Any particular issues you have ran into with older versions?

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/QueryBuilder.php
> +                $this->usingTable($this->getQualifiedFieldNameFromRelation($aggregateDescriptor['relation']), function () use ($request, $query, $aggregateDescriptor) {
Please rename the `$query` here to something like `aggregateQuery` to avoid confusion with the actual base query object. It may seem at first that filters are applied to the base one, rather than the aggregate one.

2022-10-16 08:48 UTC, alexzarbn commented on src/Drivers/Standard/QueryBuilder.php
> +                        $this->applyFiltersToQuery($query, $request, $this->removeFieldPrefixFromFields($includeDescriptor['filters'] ?? [], $includeDescriptor['relation'].'.'));
Here too, please use something like `includeQuery`, rather than just `query` to avoid confusion with the base query.

2022-10-16 08:48 UTC, alexzarbn commented on src/Helper/ArrayHelper.php
> +namespace Orion\Helper;
`Helpers` :)

2022-10-16 08:48 UTC, alexzarbn commented on src/Helper/Helper.php
> +abstract class Helper
I do not think a base class is required - neither of two introduced helpers share any common logic.

2022-10-16 08:48 UTC, alexzarbn commented on src/Helper/RequestHelper.php
> +    public static function getPostRequestParam($key = null, $default = null) {
This also seems like a hack 🤔 Even if query and post params are returned together for some reason - is it really an issue? They are named differently - no collision there.

2022-10-16 08:48 UTC, alexzarbn commented on src/Http/Controllers/RelationController.php
> +            $this->relationQueryBuilder->applyFiltersToQuery($query, App::make(Request::class));
Feels like it shouldn't be here - filters are applied only on search endpoint in `QueryBuilder` and only when it is not in intermediate mode. Any particular reason for putting it here?

2022-10-16 08:48 UTC, alexzarbn commented on src/Http/Controllers/RelationController.php
> +            $this->relationQueryBuilder->applyIncludesToQuery($query, App::make(Request::class));
The same question as for the filters

2022-10-16 08:48 UTC, alexzarbn commented on src/Http/Rules/WhitelistedQueryFields.php
> +class WhitelistedQueryFields implements Rule
Why not reuse the `WhitelistedFields` rule?

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/ParamsValidator.php
> +                    'aggregate.*.relation' => [
That's what I did before but I changed it because it was impossible to validate. I could easily throw a SQL exception which is I think what we don't want. "Exists" and "Count" aggregate doesn't work like others so I tought we might want to manage the API consumer experience ?

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/ParamsValidator.php
> +                'aggregateCount' => ['sometimes', 'string', 'not_regex:/\\./', new WhitelistedQueryFields($this->aggregatableBy)],
I had that in mind but couldn't figure a right naming, thanks :)

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +    protected function usingTable($table, $callback) {
Basically when you are using a callback on an aggregate / includes, the table you are refering to is not the current one but the one of the relation. I worked on this PR to make it consistent with current implementation of Orion so when you filter on includes you refer to distant table ("relation": "posts", "filters": "posts.id >5") orion translate it easily but the current code force the table to the resource one which was not a problem for filtering at first. If you have any idea how to achieve this, i'm all listening :D

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +    public function getQualifiedFieldNameFromRelation(string $relation):string
Effectivly ! Thanks

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +                "Aggregate queries are only supported with Laravel 8 and later"
Yes it is but the naming is quite different. I might need help supporting older versions if you can. Not only this function but also the tests, even thought i'll took time to investigate this day 😄

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +                $this->usingTable($this->getQualifiedFieldNameFromRelation($aggregateDescriptor['relation']), function () use ($request, $query, $aggregateDescriptor) {
I'm on it !

2022-10-16 10:13 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +                        $this->applyFiltersToQuery($query, $request, $this->removeFieldPrefixFromFields($includeDescriptor['filters'] ?? [], $includeDescriptor['relation'].'.'));
I'm on it !

2022-10-16 10:13 UTC, GautierDele commented on src/Helper/Helper.php
> +abstract class Helper
I can remove it, I thought it would be usefull in the future

2022-10-16 10:13 UTC, GautierDele commented on src/Helper/RequestHelper.php
> +    public static function getPostRequestParam($key = null, $default = null) {
This clearly is an hack, for some reason, "->post()" doesn't work the same on older version. Symfony's request gives post params to the "request->request". I couldn't figure any better way to avoid this if you have one

2022-10-16 10:13 UTC, GautierDele commented on src/Http/Controllers/RelationController.php
> +            $this->relationQueryBuilder->applyFiltersToQuery($query, App::make(Request::class));
I'm not quite sure where this function is used. Do you mean it should be in an other part of the code or it's not needed ?

2022-10-16 10:13 UTC, GautierDele commented on src/Http/Rules/WhitelistedQueryFields.php
> +class WhitelistedQueryFields implements Rule
Because when you validate query fields, those are specified comma seperated. Do you have any better idea implementing this ?

2022-10-16 17:42 UTC, GautierDele commented
Can I have your help with those tests @alexzarbn i did set up an environment on my side with php 7.4 and Laravel 6 using your sample projet and i can't manage to reproduce the error giving by automation ...
![image](https://user-images.githubusercontent.com/12382966/196050016-89130f90-fdb7-4589-9714-32f5b5ad25e6.png)

2022-10-17 08:37 UTC, alexzarbn commented on src/Drivers/Standard/ParamsValidator.php
> +                    'aggregate.*.relation' => [
Oh, right, that makes sense, let's leave it as is then 👍

2022-10-17 08:40 UTC, alexzarbn commented on src/Helper/RequestHelper.php
> +    public static function getPostRequestParam($key = null, $default = null) {
I will take a look at this part of the code once the PR is merged 👌🏻 Seems like requires some investigation.

2022-10-17 08:45 UTC, alexzarbn commented on src/Http/Controllers/RelationController.php
> +            $this->relationQueryBuilder->applyFiltersToQuery($query, App::make(Request::class));
This function is used in each and every endpoint for constructing a base query. The base query is then passed into the `QueryBuilder` where filters and everything is applied. It's not needed here, basically.

2022-10-17 08:49 UTC, alexzarbn commented on src/Http/Rules/WhitelistedQueryFields.php
> +class WhitelistedQueryFields implements Rule
The logic of handling a single field is basically the same. A better approach would be to reuse the `WhitelistedFields` rule inside the `WhitelistedQueryFields` rule so that the logic is not duplicated.

2022-10-17 08:51 UTC, alexzarbn requested changes
Suggested some architectural improvements, the rest looks fine 🔥
As for the tests - I will try to identify the issue.

2022-10-17 11:01 UTC, GautierDele commented on src/Helper/RequestHelper.php
> +    public static function getPostRequestParam($key = null, $default = null) {
I did allow you to commit to the repository if you want to have a look before merging 😉

2022-10-17 21:34 UTC, GautierDele commented on src/Drivers/Standard/ParamsValidator.php
> +        $depth = $this->nestedFiltersDepth(RequestHelper::getPostRequestParam('aggregate', []), -1);
Done

2022-10-17 21:41 UTC, GautierDele commented on src/Http/Controllers/RelationController.php
> +            $this->relationQueryBuilder->applyFiltersToQuery($query, App::make(Request::class));
I'm not quite sure of this, i'm getting unvalidated tests when applying this with missing includes

2022-10-17 21:43 UTC, GautierDele commented on src/Http/Rules/WhitelistedQueryFields.php
> +class WhitelistedQueryFields implements Rule
Done

2022-10-17 21:49 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +    protected function usingTable($table, $callback) {
You want to use multiple query builders in one query ? We might want to refactor the current query builder better ?

2022-10-17 21:49 UTC, GautierDele commented on src/Drivers/Standard/ParamsValidator.php
> +        $depth = $this->nestedFiltersDepth(RequestHelper::getPostRequestParam('aggregate', []), -1);
with "includes" too for post params

2022-10-17 22:21 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +                "Aggregate queries are only supported with Laravel 8 and later"
I had a closer look and basically you can only do a "withCount" with Laravel 7 which might be a pain to implement due to technical debt for such a small feature

2022-10-17 22:26 UTC, GautierDele commented on src/Drivers/Standard/QueryBuilder.php
> +                "Aggregate queries are only supported with Laravel 8 and later"
Also you can't filter on "withCount"

2022-10-17 22:38 UTC, GautierDele commented on src/Http/Controllers/RelationController.php
> +            $this->relationQueryBuilder->applyFiltersToQuery($query, App::make(Request::class));
Basically it doesn't work because when you are in intermediate mode the current table is not good, it refers to your other point to specify multiple query builders to avoid "usingTable". We might want to refactor the code to avoid this but I don't think it's related to this PR

2022-10-18 13:34 UTC, alexzarbn commented on src/Drivers/Standard/QueryBuilder.php
> +    protected function usingTable($table, $callback) {
Yes, newly instantiated query builder instance would solely work with a provided relation model, not causing any potential interference. Replacing just the table in a current query builder instance may potential cause unexpected behavior down the road, even if it is used under a callback and is reset back.

2022-10-18 13:35 UTC, merged