:sparkles: pagination limit
tailflow/laravel-orion pull request #186
Opened 2022-10-18 20:57 UTC by GautierDele

closes #185

This basically allows to specify pagination limit and avoid possibility to crash your API or overuse the mysql server.

TODO:
[ ] Documentation

2022-10-19 07:05 UTC, jasper-ter-veen commented on src/Http/Controllers/BaseController.php
> +    protected $paginationLimit = 500;
Shouldn't this be an optional, configurable setting?

2022-10-19 07:41 UTC, GautierDele commented on src/Http/Controllers/BaseController.php
> +    protected $paginationLimit = 500;
I dont think so, you can increase the limit if you are willing to but if you dont need pagination you should use a non paginated controller in my opinion

2022-10-19 08:54 UTC, jasper-ter-veen commented on src/Http/Controllers/BaseController.php
> +    protected $paginationLimit = 500;
OK, Fair point. You can resolve this thread.

2022-10-19 09:28 UTC, alexzarbn requested changes

2022-10-19 09:28 UTC, alexzarbn commented on src/Http/Controllers/BaseController.php
> +                'maxLimit' => $this->paginationLimit
@GautierDele My OCD is suggesting to make it a method too, just like the `limit()` method 😄
Also, perhaps rename to `maxLimit()` to avoid confusion between those two.

2022-10-20 19:24 UTC, GautierDele commented on src/Http/Controllers/BaseController.php
> +                'maxLimit' => $this->paginationLimit
@alexzarbn that's done, I also changed a query param that wasn't good from previous PR

2022-10-20 19:31 UTC, GautierDele commented
@alexzarbn doc has been updated in https://github.com/tailflow/laravel-orion-docs/pull/36
So you can change both if you want 😄

2022-10-21 12:26 UTC, GautierDele commented
@alexzarbn also please notify in the upgrade guide that it could be a breaking change
We might want to update the middle version: v2.17.0

2022-10-23 10:46 UTC, alexzarbn commented
@GautierDele  Awesome, thanks, merging ~

2022-10-23 10:47 UTC, merged