Prevent query builder from overwriting scopes
tailflow/laravel-orion pull request #257
Opened 2024-05-19 20:53 UTC by JonErickson

This PR is directly related to #256. Due to `applyIncludesToQuery` being after any of the filtering/scoping for a search endpoint, if your scope eager loads any of the same relationships as in the `include` parameter, the scope is overwritten and thus no longer applies. This PR simply reorders the query modifiers so that your explicit scope declarations will always take precedence.

Endpoint: /api/tasks/search?include=users
Scope:
```
public function scopeSomething(Builder $query): void
{
    $query->with(['users' => fn($query) => do something ]);
}
```

Scope would not be applied since the include is also eager loading the relationship and would take precedence.

2024-05-20 14:35 UTC, alexzarbn commented
Hi @JonErickson,

Thank you for spotting this issue! Could you please include an integration test that covers that scenario as well?

2024-05-20 14:36 UTC, alexzarbn requested changes
Hi @JonErickson,

Thank you for spotting this issue! Could you please include an integration test that covers that scenario as well?

2024-05-20 17:28 UTC, JonErickson commented
Tests added. If you remove the scope, or change the query modifiers in `QueryBuilder.php` back to the original ordering, the test will fail as the dates will result to default ordering.

2024-05-24 15:16 UTC, JonErickson commented
Any update @alexzarbn?

2024-06-02 05:04 UTC, merged